// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMatchPoints = `-- name: AddMatchPoints :exec
UPDATE cards SET match_points = match_points + $1::int, updated_at = now()
WHERE uuid::text = $2
`

type AddMatchPointsParams struct {
	Column1 int32
	Uuid    string
}

func (q *Queries) AddMatchPoints(ctx context.Context, arg AddMatchPointsParams) error {
	_, err := q.db.Exec(ctx, addMatchPoints, arg.Column1, arg.Uuid)
	return err
}

const confirmCard = `-- name: ConfirmCard :exec
UPDATE cards SET word = $1, is_confirmed = true, expires_at = NULL, updated_at = now()
WHERE id = $2
`

type ConfirmCardParams struct {
	Word string
	ID   int64
}

func (q *Queries) ConfirmCard(ctx context.Context, arg ConfirmCardParams) error {
	_, err := q.db.Exec(ctx, confirmCard, arg.Word, arg.ID)
	return err
}

const countCardsByThemeID = `-- name: CountCardsByThemeID :one
SELECT COUNT(*) FROM cards WHERE theme_id = $1
`

func (q *Queries) CountCardsByThemeID(ctx context.Context, themeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCardsByThemeID, themeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getAvailableCardNumber = `-- name: GetAvailableCardNumber :one
SELECT n::int FROM generate_series($1::int, $2::int) AS n
WHERE n NOT IN (SELECT card_number FROM cards WHERE theme_id = $3)
ORDER BY random()
LIMIT 1
`

type GetAvailableCardNumberParams struct {
	Column1 int32
	Column2 int32
	ThemeID int64
}

func (q *Queries) GetAvailableCardNumber(ctx context.Context, arg GetAvailableCardNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getAvailableCardNumber, arg.Column1, arg.Column2, arg.ThemeID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, uuid, theme_id, profile_id, guest_name, card_number, word, is_confirmed, match_points, expires_at, created_at, updated_at FROM cards WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id int64) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ThemeID,
		&i.ProfileID,
		&i.GuestName,
		&i.CardNumber,
		&i.Word,
		&i.IsConfirmed,
		&i.MatchPoints,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardsByUUIDs = `-- name: GetCardsByUUIDs :many
SELECT id, uuid, theme_id, profile_id, guest_name, card_number, word, is_confirmed, match_points, expires_at, created_at, updated_at FROM cards WHERE uuid::text = ANY($1::text[])
`

func (q *Queries) GetCardsByUUIDs(ctx context.Context, dollar_1 []string) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCardsByUUIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ThemeID,
			&i.ProfileID,
			&i.GuestName,
			&i.CardNumber,
			&i.Word,
			&i.IsConfirmed,
			&i.MatchPoints,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameCards = `-- name: GetGameCards :many
SELECT id, uuid, theme_id, profile_id, guest_name, card_number, word, is_confirmed, match_points, expires_at, created_at, updated_at FROM cards
WHERE theme_id = $1 AND is_confirmed = true
ORDER BY random()
LIMIT $2::int
`

type GetGameCardsParams struct {
	ThemeID int64
	Column2 int32
}

func (q *Queries) GetGameCards(ctx context.Context, arg GetGameCardsParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, getGameCards, arg.ThemeID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ThemeID,
			&i.ProfileID,
			&i.GuestName,
			&i.CardNumber,
			&i.Word,
			&i.IsConfirmed,
			&i.MatchPoints,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCard = `-- name: InsertCard :one
INSERT INTO cards (theme_id, profile_id, guest_name, card_number, word, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid
`

type InsertCardParams struct {
	ThemeID    int64
	ProfileID  pgtype.Int8
	GuestName  pgtype.Text
	CardNumber int16
	Word       string
	ExpiresAt  pgtype.Timestamptz
}

type InsertCardRow struct {
	ID   int64
	Uuid string
}

func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) (InsertCardRow, error) {
	row := q.db.QueryRow(ctx, insertCard,
		arg.ThemeID,
		arg.ProfileID,
		arg.GuestName,
		arg.CardNumber,
		arg.Word,
		arg.ExpiresAt,
	)
	var i InsertCardRow
	err := row.Scan(&i.ID, &i.Uuid)
	return i, err
}
