// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID string
}

type Card struct {
	ID          int64
	Uuid        string
	ThemeID     int64
	ProfileID   pgtype.Int8
	GuestName   pgtype.Text
	CardNumber  int16
	Word        string
	IsConfirmed bool
	MatchPoints int32
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlayRecord struct {
	ID          int64
	ThemeID     int64
	ProfileID   pgtype.Int8
	CardAmount  int16
	CorrectRate float64
	CreatedAt   time.Time
}

type Profile struct {
	ID         int64
	AuthUserID string
	UserName   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Theme struct {
	ID        int64
	Title     string
	CreatedBy pgtype.Int8
	CreatedAt time.Time
}
