// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_record.sql

package sqlcgen

import (
	"context"
)

const insertPlayRecord = `-- name: InsertPlayRecord :exec
INSERT INTO play_records (theme_id, profile_id, card_amount, correct_rate)
VALUES ($1, $2, $3, $4)
`

type InsertPlayRecordParams struct {
	ThemeID     int64
	ProfileID   int64
	CardAmount  int16
	CorrectRate float64
}

func (q *Queries) InsertPlayRecord(ctx context.Context, arg InsertPlayRecordParams) error {
	_, err := q.db.Exec(ctx, insertPlayRecord,
		arg.ThemeID,
		arg.ProfileID,
		arg.CardAmount,
		arg.CorrectRate,
	)
	return err
}
