// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"
)

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE auth_user_id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, authUserID string) error {
	_, err := q.db.Exec(ctx, deleteProfile, authUserID)
	return err
}

const getProfileByAuthUserID = `-- name: GetProfileByAuthUserID :one
SELECT id, auth_user_id, user_name FROM profiles WHERE auth_user_id = $1
`

type GetProfileByAuthUserIDRow struct {
	ID         int64
	AuthUserID string
	UserName   string
}

func (q *Queries) GetProfileByAuthUserID(ctx context.Context, authUserID string) (GetProfileByAuthUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByAuthUserID, authUserID)
	var i GetProfileByAuthUserIDRow
	err := row.Scan(&i.ID, &i.AuthUserID, &i.UserName)
	return i, err
}

const updateProfileUserName = `-- name: UpdateProfileUserName :exec
UPDATE profiles SET user_name = $1, updated_at = now() WHERE auth_user_id = $2
`

type UpdateProfileUserNameParams struct {
	UserName   string
	AuthUserID string
}

func (q *Queries) UpdateProfileUserName(ctx context.Context, arg UpdateProfileUserNameParams) error {
	_, err := q.db.Exec(ctx, updateProfileUserName, arg.UserName, arg.AuthUserID)
	return err
}
