// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: theme.sql

package sqlcgen

import (
	"context"
)

const getAllThemes = `-- name: GetAllThemes :many
SELECT id, title FROM themes ORDER BY id
`

type GetAllThemesRow struct {
	ID    int64
	Title string
}

func (q *Queries) GetAllThemes(ctx context.Context) ([]GetAllThemesRow, error) {
	rows, err := q.db.Query(ctx, getAllThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllThemesRow
	for rows.Next() {
		var i GetAllThemesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThemeByID = `-- name: GetThemeByID :one
SELECT id, title FROM themes WHERE id = $1
`

type GetThemeByIDRow struct {
	ID    int64
	Title string
}

func (q *Queries) GetThemeByID(ctx context.Context, id int64) (GetThemeByIDRow, error) {
	row := q.db.QueryRow(ctx, getThemeByID, id)
	var i GetThemeByIDRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}
