// Code generated by MockGen. DO NOT EDIT.
// Source: card.repository.go
//
// Generated by this command:
//
//	mockgen -source=card.repository.go -destination=mock/card_mock.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	card "github.com/topi0247/hitori/domain/card"
	gomock "go.uber.org/mock/gomock"
)

// MockCardRepository is a mock of CardRepository interface.
type MockCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryMockRecorder
	isgomock struct{}
}

// MockCardRepositoryMockRecorder is the mock recorder for MockCardRepository.
type MockCardRepositoryMockRecorder struct {
	mock *MockCardRepository
}

// NewMockCardRepository creates a new mock instance.
func NewMockCardRepository(ctrl *gomock.Controller) *MockCardRepository {
	mock := &MockCardRepository{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepository) EXPECT() *MockCardRepositoryMockRecorder {
	return m.recorder
}

// AddMatchPoints mocks base method.
func (m *MockCardRepository) AddMatchPoints(ctx context.Context, uuid string, points int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMatchPoints", ctx, uuid, points)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatchPoints indicates an expected call of AddMatchPoints.
func (mr *MockCardRepositoryMockRecorder) AddMatchPoints(ctx, uuid, points any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatchPoints", reflect.TypeOf((*MockCardRepository)(nil).AddMatchPoints), ctx, uuid, points)
}

// Confirm mocks base method.
func (m *MockCardRepository) Confirm(ctx context.Context, id int64, word string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, id, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockCardRepositoryMockRecorder) Confirm(ctx, id, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockCardRepository)(nil).Confirm), ctx, id, word)
}

// CountByThemeID mocks base method.
func (m *MockCardRepository) CountByThemeID(ctx context.Context, themeID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByThemeID", ctx, themeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByThemeID indicates an expected call of CountByThemeID.
func (mr *MockCardRepositoryMockRecorder) CountByThemeID(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByThemeID", reflect.TypeOf((*MockCardRepository)(nil).CountByThemeID), ctx, themeID)
}

// Delete mocks base method.
func (m *MockCardRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCardRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCardRepository)(nil).Delete), ctx, id)
}

// FetchByID mocks base method.
func (m *MockCardRepository) FetchByID(ctx context.Context, id int64) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockCardRepositoryMockRecorder) FetchByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockCardRepository)(nil).FetchByID), ctx, id)
}

// FetchGameCardsByUUIDs mocks base method.
func (m *MockCardRepository) FetchGameCardsByUUIDs(ctx context.Context, uuids []string) ([]*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGameCardsByUUIDs", ctx, uuids)
	ret0, _ := ret[0].([]*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGameCardsByUUIDs indicates an expected call of FetchGameCardsByUUIDs.
func (mr *MockCardRepositoryMockRecorder) FetchGameCardsByUUIDs(ctx, uuids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGameCardsByUUIDs", reflect.TypeOf((*MockCardRepository)(nil).FetchGameCardsByUUIDs), ctx, uuids)
}

// GetAvailableNumber mocks base method.
func (m *MockCardRepository) GetAvailableNumber(ctx context.Context, themeID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableNumber", ctx, themeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableNumber indicates an expected call of GetAvailableNumber.
func (mr *MockCardRepositoryMockRecorder) GetAvailableNumber(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableNumber", reflect.TypeOf((*MockCardRepository)(nil).GetAvailableNumber), ctx, themeID)
}

// GetGameCards mocks base method.
func (m *MockCardRepository) GetGameCards(ctx context.Context, themeID int64, amount int) ([]*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameCards", ctx, themeID, amount)
	ret0, _ := ret[0].([]*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameCards indicates an expected call of GetGameCards.
func (mr *MockCardRepositoryMockRecorder) GetGameCards(ctx, themeID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameCards", reflect.TypeOf((*MockCardRepository)(nil).GetGameCards), ctx, themeID, amount)
}

// Save mocks base method.
func (m *MockCardRepository) Save(ctx context.Context, c *card.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCardRepositoryMockRecorder) Save(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCardRepository)(nil).Save), ctx, c)
}
