// Code generated by MockGen. DO NOT EDIT.
// Source: game.repository.go
//
// Generated by this command:
//
//	mockgen -source=game.repository.go -destination=mock/game_mock.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	repository "github.com/topi0247/hitori/usecase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayRecordRepository is a mock of PlayRecordRepository interface.
type MockPlayRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlayRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockPlayRecordRepositoryMockRecorder is the mock recorder for MockPlayRecordRepository.
type MockPlayRecordRepositoryMockRecorder struct {
	mock *MockPlayRecordRepository
}

// NewMockPlayRecordRepository creates a new mock instance.
func NewMockPlayRecordRepository(ctrl *gomock.Controller) *MockPlayRecordRepository {
	mock := &MockPlayRecordRepository{ctrl: ctrl}
	mock.recorder = &MockPlayRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayRecordRepository) EXPECT() *MockPlayRecordRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockPlayRecordRepository) Save(ctx context.Context, record *repository.PlayRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPlayRecordRepositoryMockRecorder) Save(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPlayRecordRepository)(nil).Save), ctx, record)
}
