// Code generated by MockGen. DO NOT EDIT.
// Source: profile.repository.go
//
// Generated by this command:
//
//	mockgen -source=profile.repository.go -destination=mock/profile_mock.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	domain "github.com/topi0247/hitori/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProfileRepository) Create(ctx context.Context, authUserID string, userName string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, authUserID, userName)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProfileRepositoryMockRecorder) Create(ctx, authUserID, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProfileRepository)(nil).Create), ctx, authUserID, userName)
}

// Delete mocks base method.
func (m *MockProfileRepository) Delete(ctx context.Context, authUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, authUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProfileRepositoryMockRecorder) Delete(ctx, authUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProfileRepository)(nil).Delete), ctx, authUserID)
}

// FetchByAuthUserID mocks base method.
func (m *MockProfileRepository) FetchByAuthUserID(ctx context.Context, authUserID string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByAuthUserID", ctx, authUserID)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByAuthUserID indicates an expected call of FetchByAuthUserID.
func (mr *MockProfileRepositoryMockRecorder) FetchByAuthUserID(ctx, authUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByAuthUserID", reflect.TypeOf((*MockProfileRepository)(nil).FetchByAuthUserID), ctx, authUserID)
}

// UpdateUserName mocks base method.
func (m *MockProfileRepository) UpdateUserName(ctx context.Context, authUserID, userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserName", ctx, authUserID, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserName indicates an expected call of UpdateUserName.
func (mr *MockProfileRepositoryMockRecorder) UpdateUserName(ctx, authUserID, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserName", reflect.TypeOf((*MockProfileRepository)(nil).UpdateUserName), ctx, authUserID, userName)
}
