// Code generated by MockGen. DO NOT EDIT.
// Source: theme.go
//
// Generated by this command:
//
//	mockgen -source=theme.go -destination=mock/theme_mock.go -package=domainmock
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/topi0247/hitori/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockThemeRepository is a mock of ThemeRepository interface.
type MockThemeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThemeRepositoryMockRecorder
	isgomock struct{}
}

// MockThemeRepositoryMockRecorder is the mock recorder for MockThemeRepository.
type MockThemeRepositoryMockRecorder struct {
	mock *MockThemeRepository
}

// NewMockThemeRepository creates a new mock instance.
func NewMockThemeRepository(ctrl *gomock.Controller) *MockThemeRepository {
	mock := &MockThemeRepository{ctrl: ctrl}
	mock.recorder = &MockThemeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThemeRepository) EXPECT() *MockThemeRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockThemeRepository) FetchAll(ctx context.Context) ([]*domain.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx)
	ret0, _ := ret[0].([]*domain.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockThemeRepositoryMockRecorder) FetchAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockThemeRepository)(nil).FetchAll), ctx)
}

// FetchByID mocks base method.
func (m *MockThemeRepository) FetchByID(ctx context.Context, id int64) (*domain.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(*domain.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockThemeRepositoryMockRecorder) FetchByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockThemeRepository)(nil).FetchByID), ctx, id)
}
