// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository_mock.go -package=cardmock
//

// Package cardmock is a generated GoMock package.
package cardmock

import (
	context "context"
	reflect "reflect"

	card "github.com/topi0247/hitori/domain/card"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockRepository) Confirm(ctx context.Context, id int64, word string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, id, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockRepositoryMockRecorder) Confirm(ctx, id, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockRepository)(nil).Confirm), ctx, id, word)
}

// CountByThemeID mocks base method.
func (m *MockRepository) CountByThemeID(ctx context.Context, themeID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByThemeID", ctx, themeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByThemeID indicates an expected call of CountByThemeID.
func (mr *MockRepositoryMockRecorder) CountByThemeID(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByThemeID", reflect.TypeOf((*MockRepository)(nil).CountByThemeID), ctx, themeID)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// FetchByID mocks base method.
func (m *MockRepository) FetchByID(ctx context.Context, id int64) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockRepositoryMockRecorder) FetchByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockRepository)(nil).FetchByID), ctx, id)
}

// GetAvailableNumber mocks base method.
func (m *MockRepository) GetAvailableNumber(ctx context.Context, themeID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableNumber", ctx, themeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableNumber indicates an expected call of GetAvailableNumber.
func (mr *MockRepositoryMockRecorder) GetAvailableNumber(ctx, themeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableNumber", reflect.TypeOf((*MockRepository)(nil).GetAvailableNumber), ctx, themeID)
}

// GetGameCards mocks base method.
func (m *MockRepository) GetGameCards(ctx context.Context, themeID int64, amount int) ([]*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameCards", ctx, themeID, amount)
	ret0, _ := ret[0].([]*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameCards indicates an expected call of GetGameCards.
func (mr *MockRepositoryMockRecorder) GetGameCards(ctx, themeID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameCards", reflect.TypeOf((*MockRepository)(nil).GetGameCards), ctx, themeID, amount)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, c *card.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, c)
}
